// R0.17: renders conformance/MATRIX.md from the engine results. Pure and deterministic.

import { cellCode } from './cell-code.js';
import type { HypothesisResult } from './hypotheses.js';
import {
  BROWSER_BOUNDARIES,
  ENGINES,
  NODE_BOUNDARIES,
  NODE_ENGINES,
  SOURCE_IDS,
  TEMPORAL_TYPE_NAMES,
  type Engine,
  type EngineResult,
  type SourceInfo,
} from './types.js';

const OFFENDING_LIMIT = 25;

function escapeCell(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function row(cells: readonly string[]): string {
  return `| ${cells.map(escapeCell).join(' | ')} |`;
}

function table(header: readonly string[], rows: readonly (readonly string[])[]): string[] {
  return [row(header), row(header.map(() => '---')), ...rows.map(row)];
}

function describeSource(info: SourceInfo): string {
  if (!info.available) return 'unavailable';
  const parts = [info.version ?? 'native'];
  if (info.resolvedToNative !== undefined) {
    parts.push(info.resolvedToNative ? 'resolved to native' : 'polyfill');
  }
  return parts.join(', ');
}

/** "dominant outcome with counts": codes by frequency, ties broken alphabetically. */
function countCodes(codes: readonly string[]): (readonly [string, number])[] {
  const counts = new Map<string, number>();
  for (const code of codes) counts.set(code, (counts.get(code) ?? 0) + 1);
  return [...counts].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

function isNodeEngine(engine: Engine): boolean {
  return NODE_ENGINES.some((candidate) => candidate === engine);
}

export function renderMatrix(
  results: Partial<Record<Engine, EngineResult>>,
  hypotheses: readonly HypothesisResult[],
): string {
  const lines: string[] = [
    '# Conformance matrix',
    '',
    'Generated by `npm run conformance:report` from `conformance/results/*.json`. **Do not edit by hand.**',
    '',
    'What happens to each Temporal type (columns) from each Temporal source at each structured-clone boundary, measured in real engines. Sources: S1 native `globalThis.Temporal`, S2 `temporal-polyfill`, S3 `temporal-polyfill/implementation`, S4 `@js-temporal/polyfill`. Boundaries: B1 `structuredClone`, B2 `MessageChannel`, B3 dedicated worker, B4 `BroadcastChannel`, B5 `window.postMessage`, B6 IndexedDB, B7 `history.state`, B8 `v8.serialize`/`v8.deserialize`.',
    '',
    '## Engines',
    '',
    ...table(
      ['Engine', 'Version', 'Run at', ...SOURCE_IDS],
      ENGINES.map((engine) => {
        const result = results[engine];
        if (result === undefined) return [engine, 'no result file', '', '', '', '', ''];
        return [
          engine,
          result.engineVersion,
          result.runAt,
          ...SOURCE_IDS.map((id) => describeSource(result.sources[id])),
        ];
      }),
    ),
    '',
    '## Summary',
    '',
    ...table(
      ['Engine', 'Source', 'Dominant outcome', 'Counts'],
      ENGINES.flatMap((engine) => {
        const result = results[engine];
        if (result === undefined) return [[engine, '', 'no result file', '']];
        return SOURCE_IDS.map((id) => {
          const counts = countCodes(result.cells.filter((c) => c.source === id).map(cellCode));
          return [
            engine,
            id,
            counts[0]?.[0] ?? 'no cells',
            counts.map(([code, n]) => `${code} x${String(n)}`).join(', '),
          ];
        });
      }),
    ),
    '',
    '## Hypotheses',
    '',
    ...table(
      ['ID', 'Hypothesis', 'Result'],
      hypotheses.map((h) => [h.id, h.statement, h.pass ? 'PASS' : 'FAIL']),
    ),
    '',
  ];

  for (const h of hypotheses.filter((candidate) => !candidate.pass)) {
    lines.push(`### ${h.id} offending cells (${String(h.offending.length)})`, '');
    for (const item of h.offending.slice(0, OFFENDING_LIMIT)) lines.push(`- ${item}`);
    if (h.offending.length > OFFENDING_LIMIT) {
      lines.push(`- ... and ${String(h.offending.length - OFFENDING_LIMIT)} more`);
    }
    lines.push('');
  }

  lines.push('## Details', '');
  for (const engine of ENGINES) {
    lines.push(`### ${engine}`, '');
    const result = results[engine];
    if (result === undefined) {
      lines.push('No result file.', '');
      continue;
    }
    const boundaries = isNodeEngine(engine) ? NODE_BOUNDARIES : BROWSER_BOUNDARIES;
    const codes = new Map(
      result.cells.map((c) => [`${c.source} ${c.boundary} ${c.type}`, cellCode(c)]),
    );
    lines.push(
      ...table(
        ['Source', 'Boundary', ...TEMPORAL_TYPE_NAMES],
        SOURCE_IDS.flatMap((id) =>
          boundaries.map((boundary) => [
            id,
            boundary,
            ...TEMPORAL_TYPE_NAMES.map(
              (type) => codes.get(`${id} ${boundary} ${type}`) ?? 'MISSING',
            ),
          ]),
        ),
      ),
      '',
    );
  }
  return lines.join('\n');
}
