import { describe, expect, it } from 'vitest';

import { cellCode } from '../../../conformance/cell-code.js';
import { evaluateHypotheses } from '../../../conformance/hypotheses.js';
import { renderMatrix } from '../../../conformance/matrix.js';
import { conformingResults, withCell } from './fixtures/engines.js';

describe('cellCode (R0.17)', () => {
  it('uses the R0.17 notation', () => {
    expect(cellCode({ outcome: 'ok' })).toBe('OK');
    expect(cellCode({ outcome: 'throws', detail: { errorName: 'DataCloneError' } })).toBe(
      'THROW(DataCloneError)',
    );
    expect(cellCode({ outcome: 'silent-loss', detail: { shape: '{}' } })).toBe('LOSS({})');
    expect(cellCode({ outcome: 'async-error', detail: { errorName: 'messageerror' } })).toBe(
      'ASYNC(messageerror)',
    );
    expect(cellCode({ outcome: 'timeout' })).toBe('TIMEOUT');
    expect(cellCode({ outcome: 'unavailable', detail: { reason: 'x' } })).toBe('N/A');
    expect(cellCode({ outcome: 'harness-error' })).toBe('HARNESS');
  });
});

describe('renderMatrix (R0.17)', () => {
  it('states that it is generated and must not be hand-edited', () => {
    const results = conformingResults();
    const matrix = renderMatrix(results, evaluateHypotheses(results));
    expect(matrix).toMatch(/Generated by `npm run conformance:report`.*Do not edit by hand/);
  });

  it('has a summary, a hypothesis table and one detailed table per engine', () => {
    const results = conformingResults();
    const matrix = renderMatrix(results, evaluateHypotheses(results));
    expect(matrix).toContain(
      '| node26 | S1 | THROW(DataCloneError) | THROW(DataCloneError) x32, THROW(Error) x8 |',
    );
    expect(matrix).toContain('| HY5 | no cell anywhere is ok | PASS |');
    for (const engine of ['node22', 'node24', 'node26', 'chromium', 'firefox', 'webkit']) {
      expect(matrix).toContain(`### ${engine}\n`);
    }
    expect(matrix).toContain(
      '| S1 | B8 | THROW(Error) | THROW(Error) | THROW(Error) | THROW(Error) | THROW(Error) | THROW(Error) | THROW(Error) | THROW(Error) |',
    );
    expect(matrix).toContain('| S1 | B7 | N/A | N/A | N/A | N/A | N/A | N/A | N/A | N/A |');
  });

  it('lists offending cells of failing hypotheses and escapes pipes', () => {
    const results = conformingResults();
    const firefox = results.firefox;
    if (firefox === undefined) throw new Error('fixture');
    results.firefox = withCell(firefox, 'S3', 'B1', 'Instant', {
      outcome: 'silent-loss',
      detail: { shape: '"a|b"' },
    });
    const matrix = renderMatrix(results, evaluateHypotheses(results));
    expect(matrix).toContain('| HY4 |');
    expect(matrix).toContain('### HY4 offending cells (1)\n\n- firefox S3 B1 Instant: LOSS("a|b")');
    expect(matrix).toContain('| S3 | B1 | LOSS("a\\|b") |');
  });

  it('is deterministic', () => {
    const results = conformingResults();
    const hypotheses = evaluateHypotheses(results);
    expect(renderMatrix(results, hypotheses)).toBe(renderMatrix(conformingResults(), hypotheses));
  });
});
